fresnote/routes/projects.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, send_from_directory, current_app
from pathlib import Path
from platform import system
import subprocess
from fresnote.classes import Projects
from fresnote.classes import Notebook

projects = Blueprint('projects', __name__)

"""
NOTES: 
     When calling a route with javascript, the flask redirect is not working.
     Do a redirect whithin the javascript function.
"""

@projects.route('/', methods=['GET'])
def index():
    config = current_app.config['projects_config']
    projects = Projects(config)
    return render_template('index.html', data={'projects': projects.projectsList})


@projects.route('/create', methods=['POST'])
def create():
    config = current_app.config['projects_config']
    projects = Projects(config)

    projectPath = request.form.get("newProjectPath")
    if Path(projectPath).exists():
        flash('Project path already exists.', 'danger')
        return redirect(url_for("projects.index"))

    try:
        projects.create_project(projectPath)
    except Exception as error:
        if current_app.config['logging']:
            current_app.logger.error(error)
        flash('Error while creating project.', 'danger')
        return redirect(url_for("projects.index"))

    project = Path(projectPath).name
    flash('Project created successfully.', 'success')
    return redirect(url_for("projects.load", project=project))


@projects.route('/select', methods=['POST'])
def select():
    project = request.form.getlist('project')[0]
    return redirect(url_for('projects.load', project=project))


@projects.route('/load/<project>', defaults={'notebook': None}, methods=['GET'])
@projects.route('/load/<project>/<notebook>', methods=['GET'])
def load(project, notebook):
    config = current_app.config['projects_config']
    notes = Notebook(project, config)
    sidebarData = notes.get_all_notebooks_and_chapters_for_sidebar()
    return render_template('project.html', 
                           sidebar=True,
                           search=False,
                           sidebarData=sidebarData,
                           project=project, 
                           notebook=notebook, 
                           chapter=None,
                           sections=[])



@projects.route('/<project>/add_notebook', methods=['POST'])
def add_notebook(project):
    config = current_app.config['projects_config']
    notes = Notebook(project, config)
    data = request.get_json()
    notebook = data['notebook']

    try:
        notes.add_notebook(notebook)
    except Exception as error:
        if current_app.config['logging']:
            current_app.logger.error(error)
        return 'Error while creating notebook.', 400

    return 'Notebook created.', 200


@projects.route('/<project>/add_chapter', methods=['POST'])
def add_chapter(project):
    config = current_app.config['projects_config']
    notes = Notebook(project, config)
    data = request.get_json()
    notebook = data['notebook']
    chapter = data['chapter']

    try:
        notes.add_chapter(notebook, chapter)
    except Exception as error:
        if current_app.config['logging']:
            current_app.logger.error(error)
        return 'Error while adding chapter.', 400
    return 'Chapter added successfully.', 200


@projects.route('/serve/<project>/<notebook>/<chapter>', methods=['GET', 'POST'])
def serve(project, notebook, chapter):
    config = current_app.config['projects_config']
    notes = Notebook(project, config)
    if not notes.notebook_chapter_exist(notebook, chapter):
        flash('Notebook and chapter do not exist in database.', 'danger')
        return redirect(url_for("projects.load", project=project, notebook=None))

    sidebarData = notes.get_all_notebooks_and_chapters_for_sidebar()
    sections = notes.get_all_sections_for_chapter(notebook, chapter)

    return render_template('project.html', 
                           sidebar=True,
                           sidebarData=sidebarData,
                           project=project, 
                           notebook=notebook, 
                           chapter=chapter,
                           sections=sections)


@projects.route('/<project>/view/<sectionIDs>', methods=['GET', 'POST'])
def view(project, sectionIDs):
    config = current_app.config['projects_config']
    notes = Notebook(project, config)

    if ',' in sectionIDs:
        sectionIDs = sectionIDs.split(',')
    else:
        sectionIDs = [sectionIDs]
    sectionIDs = [int(x) for x in sectionIDs]
    sections = notes.get_sections_based_on_IDs(sectionIDs)

    return render_template('project.html', 
                           sidebar=False,
                           search=False,
                           sidebarData=[],
                           project=project, 
                           notebook="", 
                           chapter="",
                           sections=sections)


@projects.route('/<project>/change_notebook_title', methods=['POST'])
def change_notebook_title(project):
    config = current_app.config['projects_config']
    notes = Notebook(project, config)
    data = request.get_json()
    previousNotebookTitle = data['previousNotebookTitle']
    newNotebookTitle = data['newNotebookTitle']

    try:
        notes.change_notebook_title(previousNotebookTitle, newNotebookTitle)
    except Exception as error:
        if current_app.config['logging']:
            current_app.logger.error(error)
        return 'Error while renaming notebook.', 400
    
    return 'Notebook renamed.', 200


@projects.route('/<project>/change_chapter_title', methods=['POST'])
def change_chapter_title(project):
    config = current_app.config['projects_config']
    notes = Notebook(project, config)
    data = request.get_json()
    previousChapterTitle = data['previousChapterTitle']
    newChapterTitle = data['newChapterTitle']
    notebook = data['notebook']

    try:
        notes.change_chapter_title(notebook, previousChapterTitle, newChapterTitle)
    except Exception as error:
        if current_app.config['logging']:
            current_app.logger.error(error)
        return 'Error while renaming chapter.', 400
    
    return 'Chapter renamed.', 200


@projects.route('/upload_file/<project>/<notebook>/<chapter>', methods=['POST'])
def upload_file(project, notebook, chapter):
    config = current_app.config['projects_config']
    notes = Notebook(project, config)
    pathToSave = Path(notes.projectUploads)

    try:
        for f in request.files.getlist('uploaded_files_for_project'):
            f.save(pathToSave.joinpath(f.filename))
    except Exception as error:
        if current_app.config['logging']:
            current_app.logger.error(error)
        flash('Error while uploading files.', 'danger')
        return redirect(url_for('projects.serve', project=project, notebook=notebook, chapter=chapter)) 

    flash('Files uploaded successfully', 'success')
    return redirect(url_for('projects.serve', project=project, notebook=notebook, chapter=chapter)) 


@projects.route('/<project>/delete_notebook_keep_sections/<notebook>', methods=['GET'])
def delete_notebook_keep_sections(project, notebook):
    config = current_app.config['projects_config']
    notes = Notebook(project, config)
    try:
        notes.delete_notebook(notebook)
    except Exception as error:
        if current_app.config['logging']:
            current_app.logger.error(error)
        return 'Error while deleting notebook.', 400
    return 'Notebook deleted.<br>Sections were kept.', 200


@projects.route('/<project>/delete_notebook_and_sections/<notebook>', methods=['GET'])
def delete_notebook_and_sections(project, notebook):
    config = current_app.config['projects_config']
    notes = Notebook(project, config)
    sectionIDs = notes.get_all_sections_ids_for_notebook(notebook)
    try:
        notes.delete_notebook(notebook)
    except Exception as error:
        if current_app.config['logging']:
            current_app.logger.error(error)
        return 'Error while deleting notebook.', 400
    if sectionIDs:
        for ID in sectionIDs:
            try:
                notes.delete_section(ID)
            except Exception as error:
                if current_app.config['logging']:
                    current_app.logger.error(error)
                return f'Error while deleting section: {ID}.', 400
    return 'Notebook and sections deleted.', 200


@projects.route('/<project>/delete_chapter_keep_sections/<notebook>/<chapter>', methods=['GET'])
def delete_chapter_keep_sections(project, notebook, chapter):
    config = current_app.config['projects_config']
    notes = Notebook(project, config)
    try:
        notes.delete_chapter_from_notebook(notebook, chapter)
    except Exception as error:
        if current_app.config['logging']:
            current_app.logger.error(error)
        return 'Error while deleting chapter.', 400
    return 'Chapter deleted.<br>Sections were kept.', 200


@projects.route('/<project>/delete_chapter_and_sections/notebook/chapter', methods=['GET'])
def delete_chapter_and_sections(project, notebook, chapter):
    config = current_app.config['projects_config']
    notes = Notebook(project, config)
    sectionIDs = notes.get_all_sections_ids_for_chapter(notebook, chapter)
    try:
        notes.delete_chapter_from_notebook(notebook, chapter)
    except Exception as error:
        if current_app.config['logging']:
            current_app.logger.error(error)
        return 'Error while deleting notebook.', 400
    if sectionIDs:
        for ID in sectionIDs:
            try:
                notes.delete_section(ID)
            except Exception as error:
                if current_app.config['logging']:
                    current_app.logger.error(error)
                return f'Error while deleting section: {ID}.', 400
    return 'Chapter and sections deleted.', 200

fresnote/templates/main.py
from flask import Flask

app = Flask(__name__)
# SECRET_KEY is necessary to flash messages that use the "session"
app.config['SECRET_KEY'] = '490FJLKWJE493'

from fresnote.routes.projects import projects
from fresnote.routes.sections import sections

# # Register routes
app.register_blueprint(projects)
app.register_blueprint(sections)

fresnote/templates/highlight_script_code.html
{% extends "main_layout.html" %}

{% block header %}
{% endblock %}

{% block content %}

    <div class="container-fluid">

        <div id="sectionsArea" class="container-fluid" style="text-align: left;">
            <p style="text-align:center"><b>file-path:</b> {{ filePath }}</p>
            <pre style="width: 75%; margin-left:auto; margin-right:auto;"><code>{{ scriptcode }}</code></pre>
        </div>
            
        </div> <!-- col -->
    </div> <!-- container fluid-->



{% endblock %}

fresnote/templates/index.html
{% extends "index_layout.html" %}

{% block header %}
{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid d-flex align-items-center">
    <div class="container">
        <div class='col-md-10 col-sm-12' style="float: none; margin: 0 auto;">
            <div class='col-md-12'>
                <h2>Load project</h2>
            </div>

            <div class='col-md-12'>
                <form action="{{ url_for('projects.select') }}" method="POST" role="form">
                    <div class="row mb-4">
                        <div class="col-md-12">
                            <select name='project' class="selectpicker" data-max-options="5" data-live-search="true" data-width="100%">
                                {% for project in data['projects'] %}
                                    <option data-tokens="{{ project }}">{{ project }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <button type="submit" class="btn col-2 btn-success text-white mb-4">Load</button>
                </form>
            </div>

            <div class='col-md-12'>
                <h2>Create project</h2>
            </div>

            <div class='col-12'>
                <form action="{{ url_for('projects.create') }}" method="POST" role="form">
                    <div class="input-group mb-3">
                        <input  name="newProjectPath" type="text" autocomplete="off" class="form-control" placeholder="Enter full path">
                        <div class="input-group-append">
                            <button class="btn btn-warning" type="submit">Create</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}

fresnote/templates/index_layout.html
<!DOCTYPE html>
<html>

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


        <!-- BOOTSTRAP CSS -->
        <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.css')}}">

        <!-- BOOTSTRAP-SELECT CSS -->
        <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap-select.min.css')}}">

        <!-- TOASTR CSS -->
        <link rel="stylesheet" href="{{url_for('static', filename='css/toastr.css')}}">

        <!-- CHOICES CSS -->
        <!-- <link rel="stylesheet" href="{{url_for('static', filename='css/choices.css')}}"> -->


        <!-- FONTAWESOME CSS -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/fontawesome.css" integrity="sha384-vd1e11sR28tEK9YANUtpIOdjGW14pS87bUBuOIoBILVWLFnS+MCX9T6MMf0VdPGq" crossorigin="anonymous">

        <!-- FRESNOTE CSS and JS -->
        <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/fresnote.css') }}">
        <script src="{{ url_for('static', filename='js/fresnote.js') }}"></script>

        <title>fresnote</title>
    </head>

    <body>


        <header class="site-header">
          {% block header %}{% endblock header %}
        </header>

        {% include 'messageArea.html' %}


<div class="wrapper">

        <!-- Page Content  -->
        <div id="content">
            {% block content %}{% endblock %}
        </div>
</div>


        <!--JQUERY JS -->
        <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> -->
        <script src="{{url_for('static', filename='js/jquery-3.6.0.min.js')}}"></script>

        <!-- TOASTR JS -->
        <script src="{{url_for('static', filename='js/toastr.min.js')}}"></script>

        <!-- BOOTSTRAP JS -->
        <script src="{{url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>

        <!-- BOOTSTRAP-SELECT JS -->
        <script src="{{url_for('static', filename='js/bootstrap-select.min.js')}}"></script>

        <!-- CHOICES JS -->
        <script src="{{url_for('static', filename='js/choices.min.js')}}"></script>

    
        <script>
            $(document).ready(function(){
                $("#myModal").modal('show');
            });
        </script>

    </body>
</html>

fresnote/templates/main_layout.html
<!DOCTYPE html>
<html>

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


        <!-- BOOTSTRAP CSS -->
        <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.css')}}">

        <!-- TOASTR CSS -->
        <link rel="stylesheet" href="{{url_for('static', filename='css/toastr.css')}}">

        <!-- HIGHLIGHT CSS -->
        <link rel="stylesheet" href="{{url_for('static', filename='css/highlight_default.css')}}">

        <!-- FONTAWESOME CSS -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/fontawesome.css" integrity="sha384-vd1e11sR28tEK9YANUtpIOdjGW14pS87bUBuOIoBILVWLFnS+MCX9T6MMf0VdPGq" crossorigin="anonymous">

        <!-- A polyfill is a piece of code (usually JavaScript on the Web) used to provide modern functionality on older browsers that do not natively support it. -->
        <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>

        <!-- CSS and JS FOR MATH RENDERING -->
        <!-- TODO: change back to using CDNs in case math rendering is not working -->
        <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="{{url_for('static', filename='css/katex.min.css')}}">
        <!-- <script src="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js" crossorigin="anonymous"></script> -->
        <script src="{{ url_for('static', filename='js/katex.min.js') }}"></script>

        <!-- QUILL CSS -->
        <link rel="stylesheet" href="{{url_for('static', filename='css/quill.snow.css')}}">

        <!-- MY CSS -->
        <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/fresnote.css') }}">


        <title>fresnote</title>
    </head>

    <body>


        <header class="site-header">
          {% block header %}{% endblock header %}
        </header>

        {% include 'messageArea.html' %}


        <!--testing start-->

<div class="wrapper">
        <!-- Sidebar  -->
        {% if sidebar %}
            <nav id="sidebar">
                {% if sidebarData|length > 0 %}
                    <ul class="list-unstyled components">
                        {% for notebook in sidebarData %}
                            <li id="sideBarli">
                                <a href="#notebook_{{ sidebarData[notebook]['notebookID'] }}" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">{{ notebook }} </a>
                        
                                <ul class="collapse list-unstyled" id="notebook_{{ sidebarData[notebook]['notebookID'] }}">
                                    {% if sidebarData[notebook]['chapters']|length > 0 %}
                                        {% for chapter in sidebarData[notebook]['chapters'] %}
                                            <li id="sideBarli">
                                                <a href="{{ url_for('projects.serve', project=project, notebook=notebook, chapter=chapter) }}">{{ chapter }}</a>
                                            </li>
                                        {% endfor %}
                                    {% endif %}

                                    <a class="btn btn-sm btn-outline-info text-dark mb-5 mt-3 pl-0" role="button" onclick="addNewChapter('{{ project }}', '{{ notebook }}');">New chapter</a>
                                </ul>


                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <ul class="list-unstyled CTAs">
                    <li>
                        <!-- TODO: change function addNewProject to addNewNotebook and pass argument project -->
                        <a class="btn btn-sm btn-info text-white mb-4" role="button" onclick="addNewNotebook('{{ project }}');">New notebook</a>
                    </li>
                    <li>
                        <a class="btn btn-sm btn-success text-white" role="button" href="{{ url_for('projects.search', project=project) }}">Search</a>
                    </li>
                </ul>
            </nav>
        {% endif %}

        <!-- Page Content  -->
        <div id="content">

            {% if sidebar %}
                <nav class="navbar navbar-expand-lg navbar-light mybg-light">
                    <div class="container-fluid">
                        <button type="button" id="sidebarCollapse" class="btn btn-info">
                            <span>Notebooks</span>
                        </button>
                        <a class="btn btn-secondary text-white" role="button" href="{{ url_for('projects.index') }}">Change project</a>
                    </div>
                </nav>

                <div class="container-fluid">
                    <div class='col-md-10 col-sm-12' style="float: none; margin: 0 auto;">
                        <div class='col-md-12'>
                            <div class='row mb-2 d-flex justify-content-center'>
                                <h3 class="text-info" id="projectSection">Project: {{ project }}</h3>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="container-fluid">
                    <div class='col-md-10 col-sm-12' style="float: none; margin: 0 auto;">
                        <div class='col-md-12'>
                            <div class='row mb-2 d-flex justify-content-center'>
                                <h3 class="text-info" id="projectSection">Sections view: {{ project }}</h3>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}

            {% block content %}{% endblock %}
        </div>
    </div>

        <!--testing end-->


        <!--JQUERY JS -->
        <script src="{{url_for('static', filename='js/jquery-3.6.0.min.js')}}"></script>

        <!-- TOASTR JS -->
        <script src="{{url_for('static', filename='js/toastr.min.js')}}"></script>

        <!-- BOOTSTRAP JS -->
        <script src="{{url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>

        <!-- HIGHLIGHT JS -->
        <script src="{{url_for('static', filename='js/highlight.min.js')}}"></script>

        <!-- ANIME JS -->
        <script src="{{url_for('static', filename='js/anime.min.js')}}"></script>

        <!-- Include the Quill library -->
        <!-- <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script> -->
        <script src="{{url_for('static', filename='js/quill.js')}}"></script>

        <!-- MY JS -->
        <script src="{{ url_for('static', filename='js/fresnote.js') }}"></script>
    
        <!-- JAVASCRIPT FOR CONTROLING SIDEBAR -->
        <script>
        $(document).ready(function () {
                    $('#sidebarCollapse').on('click', function () {
                        $('#sidebar').toggleClass('active');
                    });
                });
        </script>

        <script>
            document.addEventListener("DOMContentLoaded", function(event) { 
                var scrollpos = localStorage.getItem('scrollpos');
                if (scrollpos) window.scrollTo(0, scrollpos);
            });

            window.onbeforeunload = function(e) {
                localStorage.setItem('scrollpos', window.scrollY);
            };
        </script>

        <!-- JAVASCRIPT required for initialization of highlight.js -->
        <script>hljs.highlightAll();</script>

        <!-- ANIMATIONS -->
        <script>
            let CardsAnimation = anime({
                              targets: '.chapterSectionCard',
                              opacity: [0,1],
                              duration: 1500,
                              easing: 'easeInOutSine'
                            });
        </script>

        <!-- Filter html table function -->
        <!--TODO: change #dkTable_ to Table_-->
        <script>
            const dkFilterTable = (ID, count) => {
              const trs = document.querySelectorAll('#dkTable_'+ID+'_'+count+' tr:not(.header)')
              const filter = document.querySelector('#filterTableInput_'+ID+'_'+count).value
              const regex = new RegExp(filter, 'i')
              const isFoundInTds = td => regex.test(td.innerHTML)
              const isFound = childrenArr => childrenArr.some(isFoundInTds)
              const setTrStyleDisplay = ({ style, children }) => {
                style.display = isFound([
                  ...children // <-- All columns
                ]) ? '' : 'none' 
              }
              
              trs.forEach(setTrStyleDisplay)
            }

        </script>

        <!-- KATEX JS FOR RENDERING MATH EQUATIOS INLINE OR AS FORMULAS -->
        <script>
            var math = document.getElementsByClassName('katex-math-equation');
            for (var i = 0; i < math.length; i++) {
              katex.render(math[i].textContent, math[i], { displayMode: true });
            }
        </script>

        <script>
            var math = document.getElementsByClassName('katex-math-inline');
            for (var i = 0; i < math.length; i++) {
              katex.render(math[i].textContent, math[i], { displayMode: false });
            }
        </script>

    </body>
</html>

fresnote/templates/messageArea.html
<div class='container'>
    <div class='row mt-3'>
        <div class='col-12'>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} text-center alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
    </div>
</div>

fresnote/templates/project.html
{% extends "main_layout.html" %}

{% block header %}
{% endblock %}

{% block content %}
<div class="container-fluid">
        <div class='col-md-12 col-sm-12' style="float: none; margin: 0 auto;">
            {% if sidebar %}
                {% if search %}
                    {% include 'project_search.html' %}

                    <div class='row'>
                        {% include 'project_notebook_sections.html' %}
                    </div>
                {% elif not notebook %}
                    <div class='row'>
                        <div class='col-md-10 col-sm-12' style="float: none; margin: 0 auto;">
                            <div class='col-md-12'>
                                <h1>Choose notebook</h1>
                            </div>
                        </div>
                    </div>

                {% elif sections|length == 0 %}
                    <div class='row'>
                        {% include 'project_panel.html' %}
                    </div>

                    <div class='row'>
                        <div class='col-md-12'>
                            <button type="button" class="btn btn-secondary btn-lg btn-block mb-4" onclick="addNewSection('{{ project }}', '{{ notebook }}', '{{ chapter }}');">Add new section</button>
                        </div>
                    </div>

                {% else %}
                    <div class='row'>
                        {% include 'project_panel.html' %}
                    </div>

                    <div class='row'>
                        {% include 'project_notebook_sections.html' %}
                    </div>

                    <div class='row'>
                        <div class='col-md-12'>
                            <button type="button" class="btn btn-secondary btn-lg btn-block mb-4" onclick="addNewSection('{{ project }}', '{{ notebook }}', '{{ chapter }}');">Add new section</button>
                        </div>
                    </div>

                {% endif %}
            {% else %}
                <div class='row'>
                    {% include 'project_notebook_sections.html' %}
                </div>
            {% endif %}
        </div>
</div>
{% endblock %}

fresnote/templates/project_panel.html
<div class='col-md-12'>
    <div class='row mb-2'>
        <!--TODO: change javascript function editProject to editNotebook-->
        <a id="editNotebookButton" class="btn btn-sm btn-outline-info ml-4 mr-2 mt-1 text-white pb-0 pt-1 text-info" role="button" onclick="editNotebook();">Edit</a>
        <!--TODO: change javascript function saveProject to saveNotebook-->
        <a id="saveNotebookButton" class="btn btn-sm btn-outline-success float-right mr-2 mt-1 pb-0 pt-1 disabled text-success" role="button" onclick="saveNotebook('{{ project }}', '{{ notebook }}', '{{ chapter }}');">Save</a>
        <h1 id="notebookSection">{{ notebook }}</h1>
    </div>

    <div class='row'>
        <a id="editChapterButton" class="btn btn-sm btn-outline-info ml-4 mr-2 text-info pb-0 pt-1" role="button" onclick="editChapter();">Edit</a>
        <!--TODO: include the argument project to saveChapter javascript function-->
        <a id="saveChapterButton" class="btn btn-sm btn-outline-success text-success float-right mr-2 pb-0 pt-1 disabled" role="button" onclick="saveChapter('{{ project }}', '{{ notebook }}', '{{ chapter }}');">Save</a>
        <h1 id="chapterSection">{{ chapter }}</h1>
    </div>

    <button class="col-1 btn btn-sm btn-outline-secondary ml-2 mr-2 mb-4 text-white pb-0 pt-1 text-info" type="button" data-toggle="collapse" data-target="#sectionsOrderSection" aria-expanded="false" aria-controls="sectionsOrderSection">
        Panel
    </button>

    <div class="collapse" id="sectionsOrderSection">

        <hr>

        <div class="mb-4 ml-2">
            <h3>Add/Change order of sections</h3>
            <div>
                <a id="editSectionOrderButton" class="btn btn-sm btn-outline-info mr-2 mb-4 text-white pb-0 pt-1 text-info" role="button" onclick="editSectionOrder();">Edit</a>
                <a id="saveSectionOrderButton" class="btn btn-sm btn-outline-success mb-4 text-success pb-0 pt-1 text-info disabled" role="button" onclick="saveSectionOrder('{{ project }}', '{{ notebook }}', '{{ chapter }}');">Save</a>
            </div>
            <div id="sectionsOrderText">
                {% if sections|length > 0 %}
                    {% for section in sections %}
                        {{ section['ID'] }}-{{ section['section'] }} <br>
                    {% endfor %}
                {% endif %}
            </div>
        </div>

        <hr>

        <div class='mb-4 ml-2'>
            <h3>Upload file(s) to notebook</h3>
            <form action="{{ url_for('projects.upload_file', project=project, notebook=notebook, chapter=chapter) }}" method="POST", enctype="multipart/form-data">
                <div class="form-group">
                    <input type="file" name="uploaded_files_for_project" class="form-control-file" id="{{ project }}UploadFile" multiple>
                    <button type="submit" class="btn btn-success text-white mb-4 mt-2">Submit</button>
                </div>
            </form>
        </div>

        <hr>

        <div class='mb-4 ml-2'>
            <h3>Delete notebook or chapter</h3>
            <!--TODO: rename javascript deleteProject to deleteNotebook-->
            <a id="deleteNotebookButton" class="btn btn-sm btn-outline-danger mb-4 text-danger" role="button" onclick="deleteNotebook('{{ project }}', '{{ notebook }}');">Delete notebook: {{ notebook }}</a>
            <br>
            <a id="deleteChapterButton" class="btn btn-sm btn-outline-danger mb-4 text-danger" role="button" onclick="deleteChapter('{{ project }}', '{{ notebook }}', '{{ chapter }}');">Delete chapter: {{ chapter }}</a>
        </div>

        <hr>

    </div>

</div>